"use client";
import { useState } from "react";
import ModuleHeader from "@/src/components/ui/module-header";
import { Button } from "@/src/components/ui/button";
import { Input } from "@/src/components/ui/input";
import PopupModal from "@/src/components/ui/popup-modal";
import { submitSupportRequest } from "@/src/api/support/support.service";
import { toApiError } from "@/src/api/client";

type Feature = "SpendIQ" | "CreditLens" | "LoanSense" | "Transact" | "Banking Operations";
const faqs: Record<Feature, [string,string][]> = { SpendIQ: [["Why are expenses missing?","Check your month and category filters, then refresh."],["Why is my total incorrect?","Review duplicate or manually added entries first."]], CreditLens: [["Why is my score unavailable?","Additional profile or financial information may be required."],["How do I dispute an item?","Send support the affected item and supporting details."]], LoanSense: [["How is eligibility calculated?","It considers income, liabilities, credit data and policy rules."],["Why is my application pending?","An officer may be reviewing documents or requesting information."]], Transact: [["Why did my transfer fail?","Check beneficiary details, balance and the OTP message."],["I did not receive an OTP.","Wait briefly, then use resend OTP. Never share your OTP."]], "Banking Operations": [["How do I report a customer onboarding issue?","Include the customer ID and the stage affected, but do not include sensitive credentials."],["What should I do when a transaction is disputed?","Review the transaction reference and follow the internal transaction-dispute process."],["How do I escalate a system issue?","Send the issue category, impact and relevant reference number to support."]] };
const themes = { SpendIQ:"spendiq", CreditLens:"creditlens", LoanSense:"loansense", Transact:"transact", "Banking Operations":"staff" } as const;
export function FeatureHelpSupportPage({feature,role="Customer",staffLayout=false}:{feature:Feature;role?:string;staffLayout?:boolean}) { const [open,setOpen]=useState(false); return <div className="space-y-6 px-1 pt-2 sm:px-2 lg:px-6 lg:pt-4 xl:px-8"><ModuleHeader theme={themes[feature]} menuMode={staffLayout ? "sidebar-overlay" : "feature-layout"} sidebarRole={staffLayout ? "BANK_OFFICER" : undefined} title="Help & Support" name="You" role={role} className="mb-6"/><main className="mx-auto max-w-4xl space-y-6"><section className="rounded-2xl border border-slate-200 bg-[#F7F6F2] p-6 shadow-sm"><h1 className="text-2xl font-semibold text-[#063154]">{feature} Help & Support</h1><p className="mt-1 text-sm text-slate-600">Find an answer or contact support securely.</p></section><section className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm"><h2 className="text-xl font-semibold text-[#063154]">Frequently asked questions</h2><div className="mt-4 space-y-2">{faqs[feature].map(([q,a])=><details key={q} className="rounded-lg border border-slate-200 bg-white/80 p-4"><summary className="cursor-pointer font-medium text-[#063154]">{q}</summary><p className="mt-2 text-sm text-slate-600">{a}</p></details>)}</div></section><section className="rounded-2xl bg-[#063154] p-6 text-white shadow-sm"><h2 className="text-xl font-semibold">Contact us</h2><p className="mt-1 text-sm text-white/80">Send an issue to the support administrator. Your signed-in email and role are attached automatically.</p><p className="mt-3 text-xs text-white/70">Never include passwords, OTPs, full account numbers, or card details.</p><Button className="mt-4 bg-[#2F9D94]" onClick={()=>setOpen(true)}>Send support request</Button></section></main><PopupModal open={open} onOpenChange={setOpen} title="Contact support"><Form feature={feature} close={()=>setOpen(false)}/></PopupModal></div>; }
function Form({feature,close}:{feature:Feature;close:()=>void}) { const [subject,setSubject]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [sending,setSending]=useState(false); async function send(){setError("");if(!subject.trim()||!message.trim()){setError("Add a subject and message.");return;}setSending(true);try{await submitSupportRequest({category:feature,subject,message});close();}catch(e){setError(toApiError(e).message);}finally{setSending(false);}} return <div className="space-y-3"><Input placeholder="Subject" value={subject} onChange={e=>setSubject(e.target.value)}/><textarea className="min-h-32 w-full rounded-md border p-3" placeholder="Describe the issue without sensitive information" maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)}/>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={close}>Cancel</Button><Button className="bg-[#2F9D94]" disabled={sending} onClick={send}>{sending?"Sending...":"Send request"}</Button></div></div>; }
