--
-- PostgreSQL database dump
--

\restrict itaoAgzxht4RJR65s4UcVXKn0SmFUpWxyBxYzN3QBWLGmoBupONua1w6rYJadU2

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-06-18 11:58:41

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 24618)
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    account_id bigint NOT NULL,
    account_number character varying(30) NOT NULL,
    account_type character varying(30) NOT NULL,
    balance numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 24617)
-- Name: accounts_account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 294 (class 1259 OID 32795)
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    audit_log_id bigint NOT NULL,
    action_type character varying(80) NOT NULL,
    actor_name character varying(150) NOT NULL,
    actor_role character varying(60),
    created_at timestamp(6) without time zone NOT NULL,
    details character varying(500),
    ip_address character varying(64),
    target_id character varying(100),
    target_type character varying(50),
    title character varying(255) NOT NULL,
    tone character varying(20) NOT NULL,
    actor_user_id bigint
);


--
-- TOC entry 293 (class 1259 OID 32794)
-- Name: audit_logs_audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN audit_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 266 (class 1259 OID 25068)
-- Name: bank_credit_evaluations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_credit_evaluations (
    bank_evaluation_id bigint NOT NULL,
    active_facilities_count integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    credit_utilization_ratio numeric(10,4) NOT NULL,
    dti_points integer NOT NULL,
    dti_ratio numeric(10,4) NOT NULL,
    evaluation_source character varying(30) NOT NULL,
    exposure_points integer NOT NULL,
    income_stability_points integer NOT NULL,
    missed_payments_count integer NOT NULL,
    payment_history_points integer NOT NULL,
    remarks text,
    report_generated boolean NOT NULL,
    risk_level character varying(20) NOT NULL,
    total_card_limit numeric(15,2) NOT NULL,
    total_card_outstanding numeric(15,2) NOT NULL,
    total_monthly_debt_payment numeric(15,2) NOT NULL,
    total_monthly_income numeric(15,2) NOT NULL,
    total_risk_points integer NOT NULL,
    utilization_points integer NOT NULL,
    bank_customer_id bigint NOT NULL,
    bank_record_id bigint NOT NULL,
    evaluated_by_officer_id bigint NOT NULL
);


--
-- TOC entry 265 (class 1259 OID 25067)
-- Name: bank_credit_evaluations_bank_evaluation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_credit_evaluations ALTER COLUMN bank_evaluation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_credit_evaluations_bank_evaluation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 24897)
-- Name: bank_customer_beneficiaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_customer_beneficiaries (
    beneficiary_id bigint NOT NULL,
    beneficiary_account_no character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nick_name character varying(100) NOT NULL,
    remark character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    bank_customer_id bigint NOT NULL
);


--
-- TOC entry 249 (class 1259 OID 24896)
-- Name: bank_customer_beneficiaries_beneficiary_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_customer_beneficiaries ALTER COLUMN beneficiary_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_customer_beneficiaries_beneficiary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 24910)
-- Name: bank_customer_cards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_customer_cards (
    card_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    credit_limit numeric(15,2) NOT NULL,
    outstanding_balance numeric(15,2) NOT NULL,
    provider character varying(100),
    bank_record_id bigint NOT NULL
);


--
-- TOC entry 251 (class 1259 OID 24909)
-- Name: bank_customer_cards_card_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_customer_cards ALTER COLUMN card_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_customer_cards_card_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 286 (class 1259 OID 25323)
-- Name: bank_customer_crib_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_customer_crib_requests (
    crib_request_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone,
    report_status character varying(20) NOT NULL,
    request_status character varying(20) NOT NULL,
    request_type character varying(30) NOT NULL,
    requested_at timestamp(6) without time zone NOT NULL,
    response_received_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    bank_customer_id bigint NOT NULL,
    requested_by_officer_id bigint NOT NULL
);


--
-- TOC entry 285 (class 1259 OID 25322)
-- Name: bank_customer_crib_requests_crib_request_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_customer_crib_requests ALTER COLUMN crib_request_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_customer_crib_requests_crib_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 24921)
-- Name: bank_customer_financial_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_customer_financial_records (
    bank_record_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    data_source character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    bank_customer_id bigint NOT NULL,
    verified_by_officer_id bigint NOT NULL
);


--
-- TOC entry 253 (class 1259 OID 24920)
-- Name: bank_customer_financial_records_bank_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_customer_financial_records ALTER COLUMN bank_record_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_customer_financial_records_bank_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 288 (class 1259 OID 25348)
-- Name: bank_customer_incomes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_customer_incomes (
    income_id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    duration_months integer,
    employment_type character varying(30),
    income_category character varying(20) NOT NULL,
    income_stability character varying(30),
    salary_type character varying(30),
    bank_record_id bigint NOT NULL
);


--
-- TOC entry 287 (class 1259 OID 25347)
-- Name: bank_customer_incomes_income_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_customer_incomes ALTER COLUMN income_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_customer_incomes_income_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 24944)
-- Name: bank_customer_liabilities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_customer_liabilities (
    liability_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    monthly_amount numeric(15,2) NOT NULL,
    bank_record_id bigint NOT NULL
);


--
-- TOC entry 255 (class 1259 OID 24943)
-- Name: bank_customer_liabilities_liability_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_customer_liabilities ALTER COLUMN liability_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_customer_liabilities_liability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 24955)
-- Name: bank_customer_loans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_customer_loans (
    loan_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    loan_type character varying(50) NOT NULL,
    monthly_emi numeric(15,2) NOT NULL,
    remaining_balance numeric(15,2) NOT NULL,
    bank_record_id bigint NOT NULL
);


--
-- TOC entry 257 (class 1259 OID 24954)
-- Name: bank_customer_loans_loan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_customer_loans ALTER COLUMN loan_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_customer_loans_loan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 24967)
-- Name: bank_customer_missed_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_customer_missed_payments (
    missed_payment_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    missed_payments integer NOT NULL,
    bank_record_id bigint NOT NULL
);


--
-- TOC entry 259 (class 1259 OID 24966)
-- Name: bank_customer_missed_payments_missed_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_customer_missed_payments ALTER COLUMN missed_payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_customer_missed_payments_missed_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 24977)
-- Name: bank_customer_transaction_otp_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_customer_transaction_otp_logs (
    otp_log_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    otp_code_hash character varying(255) NOT NULL,
    otp_status character varying(20) NOT NULL,
    resend_count integer NOT NULL,
    sent_to_email character varying(150) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    verified_at timestamp(6) without time zone,
    transaction_id bigint NOT NULL
);


--
-- TOC entry 261 (class 1259 OID 24976)
-- Name: bank_customer_transaction_otp_logs_otp_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_customer_transaction_otp_logs ALTER COLUMN otp_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_customer_transaction_otp_logs_otp_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 24992)
-- Name: bank_customer_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_customer_transactions (
    transaction_id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expense_tracking_enabled boolean NOT NULL,
    failure_reason character varying(255),
    otp_verified boolean NOT NULL,
    receiver_account_no character varying(20) NOT NULL,
    receiver_name character varying(150) NOT NULL,
    reference_no character varying(50) NOT NULL,
    remark character varying(255) NOT NULL,
    sender_account_no character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    bank_customer_id bigint NOT NULL
);


--
-- TOC entry 263 (class 1259 OID 24991)
-- Name: bank_customer_transactions_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_customer_transactions ALTER COLUMN transaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_customer_transactions_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 24631)
-- Name: bank_customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_customers (
    bank_customer_id bigint NOT NULL,
    access_status character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_code character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    account_id bigint NOT NULL,
    branch_id bigint NOT NULL,
    officer_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 24630)
-- Name: bank_customers_bank_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_customers ALTER COLUMN bank_customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_customers_bank_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 24646)
-- Name: bank_officers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_officers (
    officer_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    employee_code character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    branch_id bigint NOT NULL,
    created_by_admin_user_id bigint,
    user_id bigint NOT NULL
);


--
-- TOC entry 227 (class 1259 OID 24645)
-- Name: bank_officers_officer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_officers ALTER COLUMN officer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_officers_officer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 24658)
-- Name: branches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.branches (
    branch_id bigint NOT NULL,
    address character varying(150),
    branch_code character varying(20) NOT NULL,
    branch_email character varying(100),
    branch_name character varying(100) NOT NULL,
    branch_phone character varying(20),
    created_at timestamp(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 24657)
-- Name: branches_branch_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.branches ALTER COLUMN branch_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branches_branch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 270 (class 1259 OID 25150)
-- Name: budget_limits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.budget_limits (
    budget_id bigint NOT NULL,
    budget_amount numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    month integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    year integer NOT NULL,
    category_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- TOC entry 269 (class 1259 OID 25149)
-- Name: budget_limits_budget_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.budget_limits ALTER COLUMN budget_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.budget_limits_budget_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 272 (class 1259 OID 25164)
-- Name: expense_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expense_categories (
    category_id bigint NOT NULL,
    category_name character varying(100) NOT NULL,
    category_type character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- TOC entry 271 (class 1259 OID 25163)
-- Name: expense_categories_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.expense_categories ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expense_categories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 274 (class 1259 OID 25175)
-- Name: expense_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expense_records (
    expense_id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expense_date date NOT NULL,
    payment_type character varying(50) NOT NULL,
    category_id bigint NOT NULL,
    user_id bigint NOT NULL,
    tracking_reference character varying(50),
    tracking_source character varying(30)
);


--
-- TOC entry 273 (class 1259 OID 25174)
-- Name: expense_records_expense_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.expense_records ALTER COLUMN expense_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expense_records_expense_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 276 (class 1259 OID 25188)
-- Name: income_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.income_records (
    income_id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    income_date date NOT NULL,
    source_name character varying(100) NOT NULL,
    user_id bigint NOT NULL
);


--
-- TOC entry 275 (class 1259 OID 25187)
-- Name: income_records_income_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.income_records ALTER COLUMN income_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.income_records_income_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 278 (class 1259 OID 25200)
-- Name: loan_eligibility_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.loan_eligibility_results (
    loan_result_id bigint NOT NULL,
    asset_value numeric(15,2),
    created_at timestamp(6) without time zone NOT NULL,
    customer_age integer NOT NULL,
    decision_reason text,
    eligibility_status character varying(30) NOT NULL,
    estimated_emi numeric(15,2) NOT NULL,
    interest_rate numeric(5,2),
    loan_type character varying(30) NOT NULL,
    recommended_max_amount numeric(15,2),
    tenure_months integer,
    loansense_evaluation_id bigint NOT NULL
);


--
-- TOC entry 277 (class 1259 OID 25199)
-- Name: loan_eligibility_results_loan_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.loan_eligibility_results ALTER COLUMN loan_result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loan_eligibility_results_loan_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 280 (class 1259 OID 25215)
-- Name: loan_policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.loan_policies (
    policy_id bigint NOT NULL,
    base_interest_rate numeric(5,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    loan_type character varying(30) NOT NULL,
    max_age integer NOT NULL,
    max_dbr_ratio numeric(5,4) NOT NULL,
    max_finance_percentage numeric(5,2),
    max_tenure_months integer NOT NULL,
    min_age integer NOT NULL,
    min_income_required numeric(15,2),
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- TOC entry 279 (class 1259 OID 25214)
-- Name: loan_policies_policy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.loan_policies ALTER COLUMN policy_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loan_policies_policy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 282 (class 1259 OID 25231)
-- Name: loansense_evaluations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.loansense_evaluations (
    loansense_evaluation_id bigint NOT NULL,
    available_emi_capacity numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    credit_card_limit numeric(15,2) NOT NULL,
    credit_card_min_payment numeric(15,2),
    credit_card_outstanding numeric(15,2) NOT NULL,
    dbr numeric(6,4) NOT NULL,
    leasing_hire_purchase_payment numeric(15,2) NOT NULL,
    max_allowed_emi numeric(15,2) NOT NULL,
    missed_payments_count integer NOT NULL,
    monthly_income numeric(15,2) NOT NULL,
    overall_status character varying(30) NOT NULL,
    remarks text,
    risk_level character varying(20) NOT NULL,
    risk_multiplier numeric(4,2) NOT NULL,
    tmdo numeric(15,2) NOT NULL,
    total_existing_loan_emi numeric(15,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    bank_customer_id bigint NOT NULL,
    bank_evaluation_id bigint NOT NULL,
    bank_record_id bigint NOT NULL
);


--
-- TOC entry 281 (class 1259 OID 25230)
-- Name: loansense_evaluations_loansense_evaluation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.loansense_evaluations ALTER COLUMN loansense_evaluation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loansense_evaluations_loansense_evaluation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 24799)
-- Name: public_customer_cards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_customer_cards (
    card_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    credit_limit numeric(15,2) NOT NULL,
    outstanding_balance numeric(15,2) NOT NULL,
    provider character varying(100),
    record_id bigint NOT NULL
);


--
-- TOC entry 239 (class 1259 OID 24798)
-- Name: public_customer_cards_card_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.public_customer_cards ALTER COLUMN card_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_customer_cards_card_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 24810)
-- Name: public_customer_financial_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_customer_financial_records (
    record_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    record_status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    public_customer_id bigint NOT NULL
);


--
-- TOC entry 241 (class 1259 OID 24809)
-- Name: public_customer_financial_records_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.public_customer_financial_records ALTER COLUMN record_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_customer_financial_records_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 290 (class 1259 OID 25359)
-- Name: public_customer_incomes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_customer_incomes (
    income_id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    duration_months integer,
    employment_type character varying(30),
    income_category character varying(20) NOT NULL,
    income_stability character varying(30),
    salary_type character varying(30),
    record_id bigint NOT NULL
);


--
-- TOC entry 289 (class 1259 OID 25358)
-- Name: public_customer_incomes_income_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.public_customer_incomes ALTER COLUMN income_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_customer_incomes_income_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 24832)
-- Name: public_customer_liabilities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_customer_liabilities (
    liability_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    monthly_amount numeric(15,2) NOT NULL,
    record_id bigint NOT NULL
);


--
-- TOC entry 243 (class 1259 OID 24831)
-- Name: public_customer_liabilities_liability_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.public_customer_liabilities ALTER COLUMN liability_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_customer_liabilities_liability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 24843)
-- Name: public_customer_loans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_customer_loans (
    loan_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    loan_type character varying(50) NOT NULL,
    monthly_emi numeric(15,2) NOT NULL,
    remaining_balance numeric(15,2) NOT NULL,
    record_id bigint NOT NULL
);


--
-- TOC entry 245 (class 1259 OID 24842)
-- Name: public_customer_loans_loan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.public_customer_loans ALTER COLUMN loan_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_customer_loans_loan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 24855)
-- Name: public_customer_missed_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_customer_missed_payments (
    missed_payment_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    missed_payments integer NOT NULL,
    record_id bigint NOT NULL
);


--
-- TOC entry 247 (class 1259 OID 24854)
-- Name: public_customer_missed_payments_missed_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.public_customer_missed_payments ALTER COLUMN missed_payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_customer_missed_payments_missed_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 24670)
-- Name: public_customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_customers (
    public_customer_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_code character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- TOC entry 231 (class 1259 OID 24669)
-- Name: public_customers_public_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.public_customers ALTER COLUMN public_customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_customers_public_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 24681)
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    refresh_token_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    last_used_at timestamp(6) without time zone,
    replaced_by_token_hash character varying(128),
    revoked boolean NOT NULL,
    token_hash character varying(128) NOT NULL,
    user_id bigint NOT NULL
);


--
-- TOC entry 233 (class 1259 OID 24680)
-- Name: refresh_tokens_refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN refresh_token_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 284 (class 1259 OID 25258)
-- Name: risk_adjustments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.risk_adjustments (
    adjustment_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    multiplier numeric(4,2) NOT NULL,
    risk_level character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- TOC entry 283 (class 1259 OID 25257)
-- Name: risk_adjustments_adjustment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.risk_adjustments ALTER COLUMN adjustment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.risk_adjustments_adjustment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 24693)
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    role_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    role_name character varying(50) NOT NULL
);


--
-- TOC entry 235 (class 1259 OID 24692)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 268 (class 1259 OID 25098)
-- Name: self_credit_evaluations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.self_credit_evaluations (
    self_evaluation_id bigint NOT NULL,
    active_facilities_count integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    credit_utilization_ratio numeric(10,4) NOT NULL,
    dti_points integer NOT NULL,
    dti_ratio numeric(10,4) NOT NULL,
    exposure_points integer NOT NULL,
    income_stability_points integer NOT NULL,
    missed_payments_count integer NOT NULL,
    payment_history_points integer NOT NULL,
    report_generated boolean NOT NULL,
    risk_level character varying(20) NOT NULL,
    total_card_limit numeric(15,2) NOT NULL,
    total_card_outstanding numeric(15,2) NOT NULL,
    total_monthly_debt_payment numeric(15,2) NOT NULL,
    total_monthly_income numeric(15,2) NOT NULL,
    total_risk_points integer NOT NULL,
    utilization_points integer NOT NULL,
    public_customer_id bigint NOT NULL,
    public_record_id bigint NOT NULL
);


--
-- TOC entry 267 (class 1259 OID 25097)
-- Name: self_credit_evaluations_self_evaluation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.self_credit_evaluations ALTER COLUMN self_evaluation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.self_credit_evaluations_self_evaluation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 292 (class 1259 OID 32773)
-- Name: transaction_otp_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaction_otp_logs (
    otp_log_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    otp_code_hash character varying(255) NOT NULL,
    otp_status character varying(20) NOT NULL,
    resend_count integer NOT NULL,
    sent_to_email character varying(150) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    verified_at timestamp(6) without time zone,
    transaction_id bigint NOT NULL
);


--
-- TOC entry 291 (class 1259 OID 32772)
-- Name: transaction_otp_logs_otp_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transaction_otp_logs ALTER COLUMN otp_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_otp_logs_otp_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 24702)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    address character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    dob date,
    email character varying(100) NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    nic character varying(20),
    password_hash character varying(255) NOT NULL,
    phone character varying(20),
    profile_picture_url character varying(500),
    province character varying(100),
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(50) NOT NULL,
    role_id bigint NOT NULL
);


--
-- TOC entry 237 (class 1259 OID 24701)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5036 (class 2606 OID 24629)
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (account_id);


--
-- TOC entry 5148 (class 2606 OID 32807)
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (audit_log_id);


--
-- TOC entry 5116 (class 2606 OID 25096)
-- Name: bank_credit_evaluations bank_credit_evaluations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_credit_evaluations
    ADD CONSTRAINT bank_credit_evaluations_pkey PRIMARY KEY (bank_evaluation_id);


--
-- TOC entry 5094 (class 2606 OID 24908)
-- Name: bank_customer_beneficiaries bank_customer_beneficiaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_beneficiaries
    ADD CONSTRAINT bank_customer_beneficiaries_pkey PRIMARY KEY (beneficiary_id);


--
-- TOC entry 5098 (class 2606 OID 24919)
-- Name: bank_customer_cards bank_customer_cards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_cards
    ADD CONSTRAINT bank_customer_cards_pkey PRIMARY KEY (card_id);


--
-- TOC entry 5140 (class 2606 OID 25336)
-- Name: bank_customer_crib_requests bank_customer_crib_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_crib_requests
    ADD CONSTRAINT bank_customer_crib_requests_pkey PRIMARY KEY (crib_request_id);


--
-- TOC entry 5100 (class 2606 OID 24931)
-- Name: bank_customer_financial_records bank_customer_financial_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_financial_records
    ADD CONSTRAINT bank_customer_financial_records_pkey PRIMARY KEY (bank_record_id);


--
-- TOC entry 5142 (class 2606 OID 25357)
-- Name: bank_customer_incomes bank_customer_incomes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_incomes
    ADD CONSTRAINT bank_customer_incomes_pkey PRIMARY KEY (income_id);


--
-- TOC entry 5102 (class 2606 OID 24953)
-- Name: bank_customer_liabilities bank_customer_liabilities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_liabilities
    ADD CONSTRAINT bank_customer_liabilities_pkey PRIMARY KEY (liability_id);


--
-- TOC entry 5104 (class 2606 OID 24965)
-- Name: bank_customer_loans bank_customer_loans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_loans
    ADD CONSTRAINT bank_customer_loans_pkey PRIMARY KEY (loan_id);


--
-- TOC entry 5106 (class 2606 OID 24975)
-- Name: bank_customer_missed_payments bank_customer_missed_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_missed_payments
    ADD CONSTRAINT bank_customer_missed_payments_pkey PRIMARY KEY (missed_payment_id);


--
-- TOC entry 5110 (class 2606 OID 24990)
-- Name: bank_customer_transaction_otp_logs bank_customer_transaction_otp_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_transaction_otp_logs
    ADD CONSTRAINT bank_customer_transaction_otp_logs_pkey PRIMARY KEY (otp_log_id);


--
-- TOC entry 5112 (class 2606 OID 25012)
-- Name: bank_customer_transactions bank_customer_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_transactions
    ADD CONSTRAINT bank_customer_transactions_pkey PRIMARY KEY (transaction_id);


--
-- TOC entry 5040 (class 2606 OID 24644)
-- Name: bank_customers bank_customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customers
    ADD CONSTRAINT bank_customers_pkey PRIMARY KEY (bank_customer_id);


--
-- TOC entry 5048 (class 2606 OID 24656)
-- Name: bank_officers bank_officers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_officers
    ADD CONSTRAINT bank_officers_pkey PRIMARY KEY (officer_id);


--
-- TOC entry 5054 (class 2606 OID 24668)
-- Name: branches branches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.branches
    ADD CONSTRAINT branches_pkey PRIMARY KEY (branch_id);


--
-- TOC entry 5120 (class 2606 OID 25162)
-- Name: budget_limits budget_limits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.budget_limits
    ADD CONSTRAINT budget_limits_pkey PRIMARY KEY (budget_id);


--
-- TOC entry 5122 (class 2606 OID 25173)
-- Name: expense_categories expense_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_categories
    ADD CONSTRAINT expense_categories_pkey PRIMARY KEY (category_id);


--
-- TOC entry 5124 (class 2606 OID 25186)
-- Name: expense_records expense_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_records
    ADD CONSTRAINT expense_records_pkey PRIMARY KEY (expense_id);


--
-- TOC entry 5126 (class 2606 OID 25198)
-- Name: income_records income_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.income_records
    ADD CONSTRAINT income_records_pkey PRIMARY KEY (income_id);


--
-- TOC entry 5128 (class 2606 OID 25213)
-- Name: loan_eligibility_results loan_eligibility_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loan_eligibility_results
    ADD CONSTRAINT loan_eligibility_results_pkey PRIMARY KEY (loan_result_id);


--
-- TOC entry 5130 (class 2606 OID 25229)
-- Name: loan_policies loan_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loan_policies
    ADD CONSTRAINT loan_policies_pkey PRIMARY KEY (policy_id);


--
-- TOC entry 5134 (class 2606 OID 25256)
-- Name: loansense_evaluations loansense_evaluations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loansense_evaluations
    ADD CONSTRAINT loansense_evaluations_pkey PRIMARY KEY (loansense_evaluation_id);


--
-- TOC entry 5082 (class 2606 OID 24808)
-- Name: public_customer_cards public_customer_cards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_cards
    ADD CONSTRAINT public_customer_cards_pkey PRIMARY KEY (card_id);


--
-- TOC entry 5084 (class 2606 OID 24819)
-- Name: public_customer_financial_records public_customer_financial_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_financial_records
    ADD CONSTRAINT public_customer_financial_records_pkey PRIMARY KEY (record_id);


--
-- TOC entry 5144 (class 2606 OID 25368)
-- Name: public_customer_incomes public_customer_incomes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_incomes
    ADD CONSTRAINT public_customer_incomes_pkey PRIMARY KEY (income_id);


--
-- TOC entry 5086 (class 2606 OID 24841)
-- Name: public_customer_liabilities public_customer_liabilities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_liabilities
    ADD CONSTRAINT public_customer_liabilities_pkey PRIMARY KEY (liability_id);


--
-- TOC entry 5088 (class 2606 OID 24853)
-- Name: public_customer_loans public_customer_loans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_loans
    ADD CONSTRAINT public_customer_loans_pkey PRIMARY KEY (loan_id);


--
-- TOC entry 5090 (class 2606 OID 24863)
-- Name: public_customer_missed_payments public_customer_missed_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_missed_payments
    ADD CONSTRAINT public_customer_missed_payments_pkey PRIMARY KEY (missed_payment_id);


--
-- TOC entry 5060 (class 2606 OID 24679)
-- Name: public_customers public_customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customers
    ADD CONSTRAINT public_customers_pkey PRIMARY KEY (public_customer_id);


--
-- TOC entry 5066 (class 2606 OID 24691)
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (refresh_token_id);


--
-- TOC entry 5136 (class 2606 OID 25267)
-- Name: risk_adjustments risk_adjustments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_adjustments
    ADD CONSTRAINT risk_adjustments_pkey PRIMARY KEY (adjustment_id);


--
-- TOC entry 5070 (class 2606 OID 24700)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- TOC entry 5118 (class 2606 OID 25122)
-- Name: self_credit_evaluations self_credit_evaluations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.self_credit_evaluations
    ADD CONSTRAINT self_credit_evaluations_pkey PRIMARY KEY (self_evaluation_id);


--
-- TOC entry 5146 (class 2606 OID 32786)
-- Name: transaction_otp_logs transaction_otp_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_otp_logs
    ADD CONSTRAINT transaction_otp_logs_pkey PRIMARY KEY (otp_log_id);


--
-- TOC entry 5056 (class 2606 OID 24732)
-- Name: branches uk1ydh5va4a9iqobwmludkv6dn1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.branches
    ADD CONSTRAINT uk1ydh5va4a9iqobwmludkv6dn1 UNIQUE (branch_email);


--
-- TOC entry 5074 (class 2606 OID 24742)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 5038 (class 2606 OID 24718)
-- Name: accounts uk6kplolsdtr3slnvx97xsy2kc8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk6kplolsdtr3slnvx97xsy2kc8 UNIQUE (account_number);


--
-- TOC entry 5072 (class 2606 OID 24740)
-- Name: roles uk716hgxp60ym1lifrdgp67xt5k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uk716hgxp60ym1lifrdgp67xt5k UNIQUE (role_name);


--
-- TOC entry 5050 (class 2606 OID 24726)
-- Name: bank_officers uk7eqqwyb733c59g14hsfih4a5k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_officers
    ADD CONSTRAINT uk7eqqwyb733c59g14hsfih4a5k UNIQUE (employee_code);


--
-- TOC entry 5132 (class 2606 OID 25269)
-- Name: loan_policies uk9dabuwcgdl45jy21mylhnvr3j; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loan_policies
    ADD CONSTRAINT uk9dabuwcgdl45jy21mylhnvr3j UNIQUE (loan_type);


--
-- TOC entry 5138 (class 2606 OID 25271)
-- Name: risk_adjustments uk9t4795ow8uap193up3l8b1qrr; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_adjustments
    ADD CONSTRAINT uk9t4795ow8uap193up3l8b1qrr UNIQUE (risk_level);


--
-- TOC entry 5096 (class 2606 OID 32788)
-- Name: bank_customer_beneficiaries uk_bank_customer_beneficiaries_customer_account; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_beneficiaries
    ADD CONSTRAINT uk_bank_customer_beneficiaries_customer_account UNIQUE (bank_customer_id, beneficiary_account_no);


--
-- TOC entry 5058 (class 2606 OID 24730)
-- Name: branches ukaqmyw20ht3aku27r3oorfaw43; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.branches
    ADD CONSTRAINT ukaqmyw20ht3aku27r3oorfaw43 UNIQUE (branch_code);


--
-- TOC entry 5062 (class 2606 OID 24734)
-- Name: public_customers ukc0el7o9xqxq3vhk2pdjx051qc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customers
    ADD CONSTRAINT ukc0el7o9xqxq3vhk2pdjx051qc UNIQUE (customer_code);


--
-- TOC entry 5064 (class 2606 OID 24736)
-- Name: public_customers ukc1y7gewai40m6tercpv9b2f6v; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customers
    ADD CONSTRAINT ukc1y7gewai40m6tercpv9b2f6v UNIQUE (user_id);


--
-- TOC entry 5042 (class 2606 OID 24720)
-- Name: bank_customers ukf5ielal7qqd3vjj66ugjol9ae; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customers
    ADD CONSTRAINT ukf5ielal7qqd3vjj66ugjol9ae UNIQUE (customer_code);


--
-- TOC entry 5052 (class 2606 OID 24728)
-- Name: bank_officers ukg0mopx2axyywr2mrn4xmjucw9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_officers
    ADD CONSTRAINT ukg0mopx2axyywr2mrn4xmjucw9 UNIQUE (user_id);


--
-- TOC entry 5044 (class 2606 OID 24724)
-- Name: bank_customers ukgwm6n62vug0isha67bcip0w4x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customers
    ADD CONSTRAINT ukgwm6n62vug0isha67bcip0w4x UNIQUE (user_id);


--
-- TOC entry 5046 (class 2606 OID 24722)
-- Name: bank_customers ukhtvsuyg048bec6e5mx7tyfawp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customers
    ADD CONSTRAINT ukhtvsuyg048bec6e5mx7tyfawp UNIQUE (account_id);


--
-- TOC entry 5076 (class 2606 OID 24744)
-- Name: users ukjc2gbki00gxj5bklyytav0xq2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukjc2gbki00gxj5bklyytav0xq2 UNIQUE (nic);


--
-- TOC entry 5114 (class 2606 OID 25016)
-- Name: bank_customer_transactions ukkeoh91qcpgdadh9d570islgol; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_transactions
    ADD CONSTRAINT ukkeoh91qcpgdadh9d570islgol UNIQUE (reference_no);


--
-- TOC entry 5092 (class 2606 OID 24865)
-- Name: public_customer_missed_payments uklrgpfjgi6d5xxwoo3x3hrmxm; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_missed_payments
    ADD CONSTRAINT uklrgpfjgi6d5xxwoo3x3hrmxm UNIQUE (record_id);


--
-- TOC entry 5068 (class 2606 OID 24738)
-- Name: refresh_tokens uko2mlirhldriil2y7krapq4frt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uko2mlirhldriil2y7krapq4frt UNIQUE (token_hash);


--
-- TOC entry 5078 (class 2606 OID 24746)
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- TOC entry 5108 (class 2606 OID 25014)
-- Name: bank_customer_missed_payments ukt8pt0txe242c54pdgl8sxp1wh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_missed_payments
    ADD CONSTRAINT ukt8pt0txe242c54pdgl8sxp1wh UNIQUE (bank_record_id);


--
-- TOC entry 5080 (class 2606 OID 24716)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 5192 (class 2606 OID 32789)
-- Name: transaction_otp_logs fk11u66e50q6nta00j4atd4r9mm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_otp_logs
    ADD CONSTRAINT fk11u66e50q6nta00j4atd4r9mm FOREIGN KEY (transaction_id) REFERENCES public.bank_customer_transactions(transaction_id);


--
-- TOC entry 5193 (class 2606 OID 32808)
-- Name: audit_logs fk17vn8rhj6qver0naebk935vkk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fk17vn8rhj6qver0naebk935vkk FOREIGN KEY (actor_user_id) REFERENCES public.users(user_id);


--
-- TOC entry 5161 (class 2606 OID 24881)
-- Name: public_customer_liabilities fk1ji2tg9i8unpx91papo20bei2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_liabilities
    ADD CONSTRAINT fk1ji2tg9i8unpx91papo20bei2 FOREIGN KEY (record_id) REFERENCES public.public_customer_financial_records(record_id);


--
-- TOC entry 5157 (class 2606 OID 24787)
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 5149 (class 2606 OID 24757)
-- Name: bank_customers fk34s29lh1u2v2uuumanlt6ok8b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customers
    ADD CONSTRAINT fk34s29lh1u2v2uuumanlt6ok8b FOREIGN KEY (officer_id) REFERENCES public.bank_officers(officer_id);


--
-- TOC entry 5153 (class 2606 OID 24777)
-- Name: bank_officers fk4a3k5vai2dp0eb7mslmoevqmv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_officers
    ADD CONSTRAINT fk4a3k5vai2dp0eb7mslmoevqmv FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 5166 (class 2606 OID 25027)
-- Name: bank_customer_financial_records fk4hrop97t55093mrsw73sbf8g8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_financial_records
    ADD CONSTRAINT fk4hrop97t55093mrsw73sbf8g8 FOREIGN KEY (bank_customer_id) REFERENCES public.bank_customers(bank_customer_id);


--
-- TOC entry 5173 (class 2606 OID 25133)
-- Name: bank_credit_evaluations fk4s60517gkfafgcjoi3y7qvflt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_credit_evaluations
    ADD CONSTRAINT fk4s60517gkfafgcjoi3y7qvflt FOREIGN KEY (evaluated_by_officer_id) REFERENCES public.bank_officers(officer_id);


--
-- TOC entry 5185 (class 2606 OID 25317)
-- Name: loansense_evaluations fk5qbcprro5hawb25darlvov3rk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loansense_evaluations
    ADD CONSTRAINT fk5qbcprro5hawb25darlvov3rk FOREIGN KEY (bank_record_id) REFERENCES public.bank_customer_financial_records(bank_record_id);


--
-- TOC entry 5168 (class 2606 OID 25042)
-- Name: bank_customer_liabilities fk66jubnbrg5wrhjp5fosav45ct; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_liabilities
    ADD CONSTRAINT fk66jubnbrg5wrhjp5fosav45ct FOREIGN KEY (bank_record_id) REFERENCES public.bank_customer_financial_records(bank_record_id);


--
-- TOC entry 5190 (class 2606 OID 25369)
-- Name: bank_customer_incomes fk6c85nb9d2kmpb0y0bkt38ic6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_incomes
    ADD CONSTRAINT fk6c85nb9d2kmpb0y0bkt38ic6 FOREIGN KEY (bank_record_id) REFERENCES public.bank_customer_financial_records(bank_record_id);


--
-- TOC entry 5169 (class 2606 OID 25047)
-- Name: bank_customer_loans fk6ulr3vfnpq33q07j5ebfr1hsa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_loans
    ADD CONSTRAINT fk6ulr3vfnpq33q07j5ebfr1hsa FOREIGN KEY (bank_record_id) REFERENCES public.bank_customer_financial_records(bank_record_id);


--
-- TOC entry 5156 (class 2606 OID 24782)
-- Name: public_customers fk850mwf01y8eos9ccgrqq9ecvu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customers
    ADD CONSTRAINT fk850mwf01y8eos9ccgrqq9ecvu FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 5170 (class 2606 OID 25052)
-- Name: bank_customer_missed_payments fk8fihuekikyrvx2blkfj01s1w8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_missed_payments
    ADD CONSTRAINT fk8fihuekikyrvx2blkfj01s1w8 FOREIGN KEY (bank_record_id) REFERENCES public.bank_customer_financial_records(bank_record_id);


--
-- TOC entry 5178 (class 2606 OID 25277)
-- Name: budget_limits fk9jw2hom1frea48swogacfc2sa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.budget_limits
    ADD CONSTRAINT fk9jw2hom1frea48swogacfc2sa FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 5176 (class 2606 OID 25143)
-- Name: self_credit_evaluations fk9xh4y5n51g5rokc97rh90ewf7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.self_credit_evaluations
    ADD CONSTRAINT fk9xh4y5n51g5rokc97rh90ewf7 FOREIGN KEY (public_record_id) REFERENCES public.public_customer_financial_records(record_id);


--
-- TOC entry 5186 (class 2606 OID 25307)
-- Name: loansense_evaluations fk9y1ujvgysel7l83i2quxj2t1t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loansense_evaluations
    ADD CONSTRAINT fk9y1ujvgysel7l83i2quxj2t1t FOREIGN KEY (bank_customer_id) REFERENCES public.bank_customers(bank_customer_id);


--
-- TOC entry 5174 (class 2606 OID 25128)
-- Name: bank_credit_evaluations fkakug9o7d4ev2l2rrs8hlvck5c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_credit_evaluations
    ADD CONSTRAINT fkakug9o7d4ev2l2rrs8hlvck5c FOREIGN KEY (bank_record_id) REFERENCES public.bank_customer_financial_records(bank_record_id);


--
-- TOC entry 5177 (class 2606 OID 25138)
-- Name: self_credit_evaluations fkarl99tpuq3nkh0wsufmwuxel3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.self_credit_evaluations
    ADD CONSTRAINT fkarl99tpuq3nkh0wsufmwuxel3 FOREIGN KEY (public_customer_id) REFERENCES public.public_customers(public_customer_id);


--
-- TOC entry 5164 (class 2606 OID 25017)
-- Name: bank_customer_beneficiaries fkc0ed9agnymacnkslx1p1exsal; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_beneficiaries
    ADD CONSTRAINT fkc0ed9agnymacnkslx1p1exsal FOREIGN KEY (bank_customer_id) REFERENCES public.bank_customers(bank_customer_id);


--
-- TOC entry 5160 (class 2606 OID 24871)
-- Name: public_customer_financial_records fkcvuvdl983ale69t2bkh74s5vx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_financial_records
    ADD CONSTRAINT fkcvuvdl983ale69t2bkh74s5vx FOREIGN KEY (public_customer_id) REFERENCES public.public_customers(public_customer_id);


--
-- TOC entry 5150 (class 2606 OID 24747)
-- Name: bank_customers fkdew50taj5ptvdw8s2hwqpo9x1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customers
    ADD CONSTRAINT fkdew50taj5ptvdw8s2hwqpo9x1 FOREIGN KEY (account_id) REFERENCES public.accounts(account_id);


--
-- TOC entry 5187 (class 2606 OID 25312)
-- Name: loansense_evaluations fkdqa02j45vtk4315u5cyl0va41; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loansense_evaluations
    ADD CONSTRAINT fkdqa02j45vtk4315u5cyl0va41 FOREIGN KEY (bank_evaluation_id) REFERENCES public.bank_credit_evaluations(bank_evaluation_id);


--
-- TOC entry 5154 (class 2606 OID 24767)
-- Name: bank_officers fke1eyjs76m52m9qcdtgibpgvfa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_officers
    ADD CONSTRAINT fke1eyjs76m52m9qcdtgibpgvfa FOREIGN KEY (branch_id) REFERENCES public.branches(branch_id);


--
-- TOC entry 5171 (class 2606 OID 25057)
-- Name: bank_customer_transaction_otp_logs fke4p1gf2461va78stu3hwy4wqr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_transaction_otp_logs
    ADD CONSTRAINT fke4p1gf2461va78stu3hwy4wqr FOREIGN KEY (transaction_id) REFERENCES public.bank_customer_transactions(transaction_id);


--
-- TOC entry 5151 (class 2606 OID 24752)
-- Name: bank_customers fke9jxqyyebf9u60t6pwm1fx8oq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customers
    ADD CONSTRAINT fke9jxqyyebf9u60t6pwm1fx8oq FOREIGN KEY (branch_id) REFERENCES public.branches(branch_id);


--
-- TOC entry 5152 (class 2606 OID 24762)
-- Name: bank_customers fkf142ppuk1uuq4m8u0jgqboy4v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customers
    ADD CONSTRAINT fkf142ppuk1uuq4m8u0jgqboy4v FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 5184 (class 2606 OID 25302)
-- Name: loan_eligibility_results fkgxae2clcm61f4cwcdh26uiia8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loan_eligibility_results
    ADD CONSTRAINT fkgxae2clcm61f4cwcdh26uiia8 FOREIGN KEY (loansense_evaluation_id) REFERENCES public.loansense_evaluations(loansense_evaluation_id);


--
-- TOC entry 5181 (class 2606 OID 25292)
-- Name: expense_records fkhrwqf8iqr8tu76vrmgk3elvb7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_records
    ADD CONSTRAINT fkhrwqf8iqr8tu76vrmgk3elvb7 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 5182 (class 2606 OID 25287)
-- Name: expense_records fki0kmswky2lkw8bbipsp3n107x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_records
    ADD CONSTRAINT fki0kmswky2lkw8bbipsp3n107x FOREIGN KEY (category_id) REFERENCES public.expense_categories(category_id);


--
-- TOC entry 5159 (class 2606 OID 24866)
-- Name: public_customer_cards fki51pk7n7acucg7fmjvhdgxvg0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_cards
    ADD CONSTRAINT fki51pk7n7acucg7fmjvhdgxvg0 FOREIGN KEY (record_id) REFERENCES public.public_customer_financial_records(record_id);


--
-- TOC entry 5179 (class 2606 OID 25272)
-- Name: budget_limits fki9y5spbgapt8l8u95gv0pkbun; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.budget_limits
    ADD CONSTRAINT fki9y5spbgapt8l8u95gv0pkbun FOREIGN KEY (category_id) REFERENCES public.expense_categories(category_id);


--
-- TOC entry 5172 (class 2606 OID 25062)
-- Name: bank_customer_transactions fkid1wmbljg4tq0uda4vdabnkc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_transactions
    ADD CONSTRAINT fkid1wmbljg4tq0uda4vdabnkc FOREIGN KEY (bank_customer_id) REFERENCES public.bank_customers(bank_customer_id);


--
-- TOC entry 5188 (class 2606 OID 25337)
-- Name: bank_customer_crib_requests fkiv99rnvcq1xlrajaie330vy26; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_crib_requests
    ADD CONSTRAINT fkiv99rnvcq1xlrajaie330vy26 FOREIGN KEY (bank_customer_id) REFERENCES public.bank_customers(bank_customer_id);


--
-- TOC entry 5162 (class 2606 OID 24886)
-- Name: public_customer_loans fkj42xtaax2i4hp1x9if48fv59r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_loans
    ADD CONSTRAINT fkj42xtaax2i4hp1x9if48fv59r FOREIGN KEY (record_id) REFERENCES public.public_customer_financial_records(record_id);


--
-- TOC entry 5180 (class 2606 OID 25282)
-- Name: expense_categories fkjbcw6agqb7ya6s33yrxfe4ymp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_categories
    ADD CONSTRAINT fkjbcw6agqb7ya6s33yrxfe4ymp FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 5165 (class 2606 OID 25022)
-- Name: bank_customer_cards fkl7g2l1t2pvobr5q7nc1n6xbui; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_cards
    ADD CONSTRAINT fkl7g2l1t2pvobr5q7nc1n6xbui FOREIGN KEY (bank_record_id) REFERENCES public.bank_customer_financial_records(bank_record_id);


--
-- TOC entry 5155 (class 2606 OID 24772)
-- Name: bank_officers fklnvv8cjj1s2ihnkk3u8tnwso3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_officers
    ADD CONSTRAINT fklnvv8cjj1s2ihnkk3u8tnwso3 FOREIGN KEY (created_by_admin_user_id) REFERENCES public.users(user_id);


--
-- TOC entry 5175 (class 2606 OID 25123)
-- Name: bank_credit_evaluations fklr0fapsououfx7fsbjv6n6c52; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_credit_evaluations
    ADD CONSTRAINT fklr0fapsououfx7fsbjv6n6c52 FOREIGN KEY (bank_customer_id) REFERENCES public.bank_customers(bank_customer_id);


--
-- TOC entry 5167 (class 2606 OID 25032)
-- Name: bank_customer_financial_records fkma11rtrqfu9w5j67v9g9cv8xd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_financial_records
    ADD CONSTRAINT fkma11rtrqfu9w5j67v9g9cv8xd FOREIGN KEY (verified_by_officer_id) REFERENCES public.bank_officers(officer_id);


--
-- TOC entry 5189 (class 2606 OID 25342)
-- Name: bank_customer_crib_requests fkmts2p88h7km3yux9j1lfxsxg9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_customer_crib_requests
    ADD CONSTRAINT fkmts2p88h7km3yux9j1lfxsxg9 FOREIGN KEY (requested_by_officer_id) REFERENCES public.bank_officers(officer_id);


--
-- TOC entry 5158 (class 2606 OID 24792)
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


--
-- TOC entry 5163 (class 2606 OID 24891)
-- Name: public_customer_missed_payments fkqf0mahykvircouqc8mcwn51x9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_missed_payments
    ADD CONSTRAINT fkqf0mahykvircouqc8mcwn51x9 FOREIGN KEY (record_id) REFERENCES public.public_customer_financial_records(record_id);


--
-- TOC entry 5183 (class 2606 OID 25297)
-- Name: income_records fkqqhdmqyp6kswcm8q5av8ei078; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.income_records
    ADD CONSTRAINT fkqqhdmqyp6kswcm8q5av8ei078 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 5191 (class 2606 OID 25374)
-- Name: public_customer_incomes fkru5nth1tci05hjgvgpeo84gyy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_customer_incomes
    ADD CONSTRAINT fkru5nth1tci05hjgvgpeo84gyy FOREIGN KEY (record_id) REFERENCES public.public_customer_financial_records(record_id);


-- Completed on 2026-06-18 11:58:42

--
-- PostgreSQL database dump complete
--

\unrestrict itaoAgzxht4RJR65s4UcVXKn0SmFUpWxyBxYzN3QBWLGmoBupONua1w6rYJadU2

